# Generated by Django 4.0.3 on 2022-04-04 17:39

from django.conf import settings
from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(game.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=models.SET(game.models.get_deleted_user), related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='game.Player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(game.models.get_deleted_user), related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
