# Generated by Django 4.0.3 on 2022-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'get_latest_by': 'modified', 'ordering': ['modified']},
        ),
    ]
