# Generated by Django 4.0.3 on 2022-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'get_latest_by': 'modified', 'ordering': ['-modified']},
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_players_in_game'),
        ),
    ]
