# Generated by Django 4.0.3 on 2022-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_options_player_unique_players_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
